# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/sd_pinout.xdc

# Block Designs: bd/data_manager/data_manager.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_manager || ORIG_REF_NAME==data_manager} -quiet] -quiet

# IP: bd/data_manager/ip/data_manager_fifo_generator_0_0/data_manager_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_manager_fifo_generator_0_0 || ORIG_REF_NAME==data_manager_fifo_generator_0_0} -quiet] -quiet

# IP: bd/data_manager/ip/data_manager_clk_wiz_0_0/data_manager_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_manager_clk_wiz_0_0 || ORIG_REF_NAME==data_manager_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/ramseyv2/repos/RunmanFPGAWavPlayer/RunmanFPGAWavPlayer.gen/sources_1/bd/data_manager/data_manager_ooc.xdc
